nucleus-ffm/foss_warn

- lib/main.dart
- lib/services/saveAndLoadSharedPreferences.dart
- lib/views/SettingsView.dart
> Add system theme option

- android/app/src/main/AndroidManifest.xml
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
- lib/class/class_alarmManager.dart
- lib/services/welcomeScreenItems.dart
- lib/views/WelcomeView.dart
- pubspec.lock
- pubspec.yaml
Sadly connected to the previous commits made in #62
> Fix alarm manager issue

- android/gradle.properties
- lib/services/welcomeScreenItems.dart
- lib/views/WelcomeView.dart
- pubspec.lock
- pubspec.yaml
- new class for the list items for the WelcomeView
- changed wording in the intro
- split WelcomeView build function in smaller functions for clarity
- remove unused variables
> Refactor WelcomeView code

- lib/class/class_WarnMessage.dart
- lib/services/welcomeScreenItems.dart
- lib/views/WelcomeView.dart
- fix api parsing
- display a check mark if battery optimization is disabled
> Fix parsing

- lib/class/abstract_Place.dart
- lib/class/class_userPreferences.dart
- lib/themes/themes.dart
- lib/views/WarningDetailView.dart
- lib/widgets/WarningWidget.dart
- lib/widgets/dialogs/ChangeLogDialog.dart
- pubspec.lock
- pubspec.yaml
- fix not saved read status of a warning when using the buttons.
> Fix not saved read status

- .github/workflows/workflow.yml
- lib/services/sortWarnings.dart
- lib/services/urlLauncher.dart
- lib/views/WarningDetailView.dart
- test/extractPhoneNumber_test.dart
- test/extractWebAddress_test.dart
- test/warningDetailView_contactField_test.dart
- Improved display of contact information
> Telephone number

- lib/services/checkForMyPlacesWarnings.dart
- lib/services/urlLauncher.dart
- lib/views/AllWarningsView.dart
- lib/views/MyPlaceDetailView.dart
- lib/views/WarningDetailView.dart
- lib/widgets/WarningWidget.dart
- test/warningDetailView_contactField_test.dart
- The last pull request didn't fix the phone number problem fully, but now it is hopefully better
- warnings that are not myPlaceWarning do not have a clickable read status button anymore as we do not save the read status and the clickable button can be confusing
> Fix broken telephone number detection and small UI fix

- android/settings.gradle
- lib/class/abstract_Place.dart
- lib/views/AllWarningsView.dart
- lib/views/MyPlaceDetailView.dart
- lib/views/MyPlacesView.dart
- lib/views/WarningDetailView.dart
- lib/widgets/WarningWidget.dart
- Fixed a bug introduced by a previous update where Etags were not used correctly 
- Quick fix for the issue with the read state #123
> Fix already read state and etags

- lib/class/class_userPreferences.dart
- lib/services/apiHandler.dart
- lib/views/WarningDetailView.dart
- lib/views/mapView.dart
- lib/widgets/dialogs/ChangeLogDialog.dart
- pubspec.yaml
There was still one edge case that was not covered by the geoJson fixer. This pull requests adds an addition case. This should fix #153 
Change alignment of the pin in the map to top center. Fix #157
> add another edge case for geoJson fixer

- lib/class/class_fpas_place.dart
- lib/class/class_user_preferences.dart
- lib/enums/sorting_categories.dart
- lib/main.dart
- lib/themes/themes.dart
- lib/widgets/dialogs/error_dialog.dart
- lib/widgets/notification_preferences_list_tile_widget.dart
> chore: format code using dart format

- lib/class/class_fpas_place.dart
- lib/main.dart
- lib/services/update_provider.dart
- lib/views/add_my_place_view.dart
- lib/views/add_my_place_with_map_view.dart
- lib/views/all_warnings_view.dart
- lib/views/dev_settings_view.dart
- lib/views/my_place_detail_view.dart
- lib/views/my_places_view.dart
- lib/widgets/dialogs/choose_theme_dialog.dart
- lib/widgets/dialogs/delete_place_dialog.dart
- lib/widgets/dialogs/error_dialog.dart
- lib/widgets/warning_widget.dart
- pubspec.lock
- pubspec.yaml
Riverpod is a more modern replacement for Provider, created by the same author because he realized there were limitations with his approach. Riverpod has various nice providers making it easier to manage state and provide services, and also features like triplestates to handle future results properly.
This PR is a simple replacement, we'll start _properly_ using it in future PRs as it'll involve a bunch of refactors.
> feat: swap out Provider for Riverpod

- lib/class/class_fpas_place.dart
- lib/class/class_unified_push_handler.dart
- lib/main.dart
- lib/services/api_handler.dart
- lib/services/check_for_my_places_warnings.dart
- lib/services/list_handler.dart
- lib/services/save_and_load_shared_preferences.dart
- lib/services/update_provider.dart
- lib/views/all_warnings_view.dart
- lib/views/dev_settings_view.dart
- lib/views/map_view.dart
- lib/views/my_place_detail_view.dart
- lib/views/my_places_view.dart
- lib/views/warning_detail_view.dart
- lib/widgets/map_widget.dart
- lib/widgets/vector_map_widget.dart
- lib/widgets/warning_widget.dart
This way it's easier to keep track of it's state and rebuild widgets when necessary.
> refactor: store saved places in a provider

- lib/class/class_fpas_place.dart
- lib/class/class_unified_push_handler.dart
- lib/l10n/app_en.arb
- lib/main.dart
- lib/services/check_for_my_places_warnings.dart
- lib/services/list_handler.dart
- lib/services/save_and_load_shared_preferences.dart
- lib/services/update_provider.dart
- lib/views/all_warnings_view.dart
- lib/views/dev_settings_view.dart
- lib/views/home/home_view.dart
- lib/views/introduction/introduction_view.dart
- lib/views/my_places_view.dart
- lib/views/warning_detail_view.dart
- lib/widgets/warning_widget.dart
- linux/flutter/ephemeral/.plugin_symlinks/flutter_local_notifications_linux
- linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
- linux/flutter/ephemeral/.plugin_symlinks/share_plus
- linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
- linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugin_registrant.h
- linux/flutter/generated_plugins.cmake
- pubspec.lock
This depends on #164, please merge that first.
The actual homescreen rewriting is not so much, it was in a pretty good state. It's mostly moving service logic to services and letting the screen do less logic.
> refactor: rewrite the home view to make it more readable

- .metadata
- README.md
- foss_warn.iml
- lib/class/class_error_logger.dart
- lib/class/class_notification_service.dart
- lib/class/class_unified_push_handler.dart
- lib/class/class_user_preferences.dart
- lib/views/home/home_view.dart
- lib/views/introduction/introduction_view.dart
- linux/.gitignore
- linux/CMakeLists.txt
- linux/de.nucleus.foss_warn.service
- linux/flutter/CMakeLists.txt
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugin_registrant.h
- linux/flutter/generated_plugins.cmake
- linux/runner/CMakeLists.txt
- linux/runner/main.cc
- linux/runner/my_application.cc
- linux/runner/my_application.h
- pubspec.lock
- pubspec.yaml
This requires a pre-release version of the next version of UnifiedPush Flutter connector for now so this is a draft.
> feat: add Linux support

- lib/class/class_area.dart
- lib/class/class_douglas_peucker.dart
- pubspec.lock
This fixes the simplification of polygons and fixes the issue that sometimes multiple duplicate polygons are stacked over each other in the map view, resulting in performance issues.
> fix polygon simplification

- lib/class/class_error_logger.dart
- lib/l10n/app_en.arb
- lib/views/log_file_viewer.dart
- lib/widgets/dialogs/error_dialog.dart
translate error dialog and the error log viewer and improve wording fix #190
> Improve error dialog

- lib/class/class_error_logger.dart
- lib/class/class_unified_push_handler.dart
- lib/class/class_user_preferences.dart
- lib/main.dart
- lib/routes.dart
- lib/services/alert_api/fpas.dart
- lib/services/legacy_handler.dart
- lib/services/save_and_load_shared_preferences.dart
- lib/services/send_status_notification.dart
- lib/services/warnings.dart
- lib/views/about_view.dart
- lib/views/add_my_place_with_map_view.dart
- lib/views/dev_settings_view.dart
- lib/views/home/home_view.dart
- lib/views/introduction/introduction_view.dart
- lib/views/introduction/widgets/base_slide.dart
- lib/views/notification_settings_view.dart
- lib/views/settings_view.dart
- lib/views/warning_detail_view.dart
- lib/widgets/connection_error_widget.dart
- lib/widgets/dialogs/choose_theme_dialog.dart
- lib/widgets/dialogs/font_size_dialog.dart
- lib/widgets/dialogs/privacy_dialog.dart
- lib/widgets/dialogs/sort_by_dialog.dart
- lib/widgets/map_widget.dart
- lib/widgets/notification_preferences_list_tile_widget.dart
This way it automatically updates the relevant parts of the app when changed.
Depends on #187.
> refactor: store user preferences in a state provider

- lib/routes.dart
- lib/services/legacy_handler.dart
- lib/views/introduction/widgets/base_slide.dart
- Fix wrong displayed icon if theme mode was set on system and platform brightness was set on dark
- fix return route if one alert is opened via the place view
- remove the old broken legacy handler and add todo for a rewrite
> minor bug fixes

- lib/class/class_fpas_place.dart
- lib/extensions/list.dart
- lib/l10n/app_en.arb
- lib/services/subscription_handler.dart
- lib/services/warnings.dart
- lib/views/my_places_view.dart
- lib/views/warnings_view.dart
- lib/widgets/connection_error_widget.dart
- lib/widgets/dialogs/invalid_subscription_dialog.dart
- lib/widgets/my_place_widget.dart
- pubspec.lock
- pubspec.yaml
This adds a dialog to easily resubscribe for expired subscriptions
> allow resubscribing for expired subscriptions

- lib/class/class_notification_service.dart
- lib/class/class_references.dart
- lib/class/class_unified_push_handler.dart
- lib/class/class_user_preferences.dart
- lib/class/class_warn_message.dart
- lib/l10n/app_en.arb
- lib/services/alert_api/fpas.dart
- lib/services/api_handler.dart
- lib/services/subscription_handler.dart
- lib/services/warnings.dart
- lib/views/dev_settings_view.dart
- lib/views/home/home_view.dart
- lib/views/my_place_detail_view.dart
- lib/views/warning_detail_view.dart
- lib/widgets/dialogs/notification_troubleshoot_dialog.dart
improve alert parsing
- only fetch and parse new alerts
- cache alerts on disk
- update and store read and notified state of alerts
depends on #211
> improve alert parsing
